src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala

java.util.Properties().getProperty returns null when the value is an object other than String. This is resulting in a runtime exception when SparkSnowflake is used in an application where other JDBC drivers co-exist.
We are facing the issue with Postgres driver which in the connect method tries to read the properties using getProperty method.
https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/Driver.java#L221

Fixed issue with objects as value in java.util.properties

---

src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/test/scala/net/snowflake/spark/snowflake/SnowflakeSourceSuite.scala

PR regarding issue #12 
calling dataframe.write() to a table that does not exist yet results in:
```
CREATE TABLE IF NOT EXISTS test_schema.test_table (id INTEGER NOT NULL, created_at TIMESTAMP, updated_at TIMESTAMP, name STRING NOT NULL, order INTEGER)
```
which fails with:
```
SQL compilation error: syntax error line 1 at position 138 unexpected ''order''.
```
whereas:
```
CREATE TABLE IF NOT EXISTS test_schema.test_table (id INTEGER NOT NULL, created_at TIMESTAMP, updated_at TIMESTAMP, name STRING NOT NULL, "order" INTEGER)
```
succeeds.
In the JDBCWrapper class, modified the schemaString method so that column names are always double-quoted in the createTableSql method in the SnowflakeWriter class. 
Added in a test case inside SnowflakeSourceSuite, which might be redundant with a …

Double quoting columns create sql

---

src/main/java/net/snowflake/spark/snowflake/s3upload/ExecutorServiceResultsHandler.java
src/main/scala/net/snowflake/spark/snowflake/SnowflakeWriter.scala

An exception in writing to S3 can result in the following stack trace.  When an exception is thrown in `SnowflakeWriter.unloadData` the StreamTransferManager was aborted and then completed.  Because an abort nulls the ExecutorCompletorService, the call to `complete` will always throw a `NullPointerException`.  To prevent a `NullPointerException`, only call `complete` on successful unload and `abort`
on unsuccessful unload.
```
java.lang.RuntimeException: java.lang.NullPointerException
at net.snowflake.spark.snowflake.s3upload.StreamTransferManager.complete(StreamTransferManager.java:223)
at net.snowflake.spark.snowflake.SnowflakeWriter$$anonfun$unloadData$4.apply(SnowflakeWriter.scala:480)
at net.snowflake.spark.snowflake.SnowflakeWriter$$anonfun$unloadData$4.apply(SnowflakeWriter.scala:41 …
```

Prevent NullPointerException from swallowing root cause on SnowflakeWrite

---

build.sbt
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala

Hi,
My org frequently queries data that's in the TIME format. Right now, it causes jobs to crash:
This PR:
1) Casts java.sql.Time to String (preventing the crash from happening)
2) Cleans up build.sbt with modern sbt syntax
We could have chosen to convert java.sql.Time to Spark's TimestampType. However, this would cause a lot of confusion among analysts who would attempt to compare "real" timestamps to "java.sql.Time" timestamps (in which the date portion is zero'd out). That implicit conversion isn't intuitive so we're better off keeping it as a string and allowing analysts to explicitly convert.
Thanks!

Fix exception when dealing with java.sql.Time

---

src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

In Append Mode the connection is writing to the table intended but not committing in the end (also autocommit is set to false) as a result, the results are not reflected in the table.

Committing changes to snowflake in Append Mode

---

src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
src/main/scala/net/snowflake/spark/snowflake/DefaultSource.scala

If we register the Snowflake data source (see: https://spark.apache.org/docs/2.1.1/api/java/index.html?org/apache/spark/sql/sources/DataSourceRegister.html), we'll be able to look it up w/o having to pass the full package name.
So...
```
spark.read.format("snowflake")
```
instead of...
```
import net.snowflake.spark.snowflake.Utils
spark.read.format(Utils.SNOWFLAKE_SOURCE_NAME) //spark.read.format("net.snowflake.spark.snowflake")
```
similar to how the other formats are registered...
```
spark.read.format("csv")
spark.read.format("avro")
spark.read.format("parquet")
```

Register the snowflake data source

---

build.sbt
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala

Support new Telemetry API sendBatchAsyc() instead of sendBatch() from jdbc 3.10.0

Support new Telemetry API sendBatchAsyc() instead of sendBatch() from jdbc 3.10.0

---

src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

Fixes errors generated when there are no files to copy: 
```
py4j.protocol.Py4JJavaError: An error occurred while calling o550.save.
: java.util.NoSuchElementException: head of empty list
at scala.collection.immutable.Nil$.head(List.scala:431)
at scala.collection.immutable.Nil$.head(List.scala:428)
at net.snowflake.spark.snowflake.io.StageWriter$.writeToStage(StageWriter.scala:59)
```

Check size of filesToUpload

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeIntegrationSuite.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

Skip CREATE TABLE when writing data to snowflake if the SaveMode is 'Append' and the target table exists. 
SNOW-125461

Skip CREATE TABLE if the SaveMode is 'Append' and table exists.

---

src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
src/main/scala/net/snowflake/spark/snowflake/test/TestHook.scala

SNOW-110427
1. Change the default value of "usestagingtable" as "off", "truncate_table" as "on". So by default, when "Overwrite" Mode is used and table exists, the old table is not re-created any more.
2. Make "truncate table" and "copy into" in one transaction when "usestagingtable" is off.
3. Introduce TEST HOOK for negative test.

Truncate and COPY INTO Target Table Transactionally

---

src/it/scala/net/snowflake/spark/snowflake/ColumnMappingIntegrationSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeWriter.scala

In Spark, if there are dot(.) in the column name, the column name should be enclosed with backtick(`). Spark connector follow this rule. 
FYI.
https://forums.databricks.com/questions/30739/how-to-deal-with-column-name-with-dot-in-pyspark-d.html
SNOW-116375

Support dot(.) in column name

---

src/it/scala/net/snowflake/spark/snowflake/ColumnMappingIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/ColumnNameCaseSuite.scala
src/it/scala/net/snowflake/spark/snowflake/DataTypesIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/DecimalIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/FilterPushdownIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/FullNewPushdownIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
src/it/scala/net/snowflake/spark/snowflake/IssueSuite.scala
src/it/scala/net/snowflake/spark/snowflake/OnErrorSuite.scala
src/it/scala/net/snowflake/spark/snowflake/SecuritySuite.scala
src/it/scala/net/snowflake/spark/snowflake/SimpleNewPushdownIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/SnowflakeIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetryIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/it/scala/net/snowflake/spark/snowflake/VariantTypeSuite.scala
src/it/scala/net/snowflake/spark/snowflake/streaming/StreamingSuite.scala

SNOW-146498
SQLContext is introduced from Spark 1.0
As of Spark 2.0, this is replaced by SparkSession.
This is for Spark 3.0 support.

Replace SQLContext with SparkSession in IT Test

---

src/main/scala/net/snowflake/spark/snowflake/streaming/SnowflakeSink.scala

SNOW-146866
In Spark 3.0, the parent class of SnowflakeSink has a conflict name 'schema'.

Rename SnowflakeSink.schema as SnowflakeSink.cachedSchema

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeWriter.scala
src/main/scala/net/snowflake/spark/snowflake/Utils.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala

1. The result is checked to send the telemetry message.
If the result format is not recognized, log a warning message
2. Send the similar telemetry message for Arrow Format
3. Replace all usages of assert() in production with readable Exception

Support new result format for COPY INTO LOCATION

---

build.sbt
src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala

When the spark task fails, this task will be rescheduled by spark until the max attempt number is arrived. So we can leverage the spark retry instead of implementing retry in spark connector. Spark sleeps 3 seconds by default before reschedule. To handle cloud storage service throttling issue, it is necessary to use exponential sleep time (spark doesn’t support it). So, we introduce extra exponential sleep time based on the task’s attempt number.

SNOW-173710 Leverage Spark retry-mechanism to handle throttling issue.

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala

1. Only spark 3.0 supports the SQL end with ';'
2. For scala 2.11, The last value in SEQ can't end with ','

SNOW-173018 Change some pushdown test case for compatibility issue

---

src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/UnsupportedStatement.scala

Before the enhancement, if generateQueries() meets unsupported
operation, it returns None, so a pushdown failure message for
"NoSuchElementException" is sent. It is unclear. With this fix,
specific info about the unsupported operation is sent.

SNOW-170311 Send specific unsupported operation in generateQueries.

---

src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/AggregationStatement.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala

Currently, telemetry message with "aggregateexpression' is sent
for unsupported aggregate function. It's unclear.

SNOW-175796 Send unsupported function name for aggregate function

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement03.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/DateStatement.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
src/test/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/PushdownSuite01.scala

Perform a format check for pushdown unix_timestamp() on string column.
Only enable the pushdown if the format is supported by Snowflake.

SNOW-180368 Add format check for unix_timestamp() pushdown

---

src/it/scala/net/snowflake/spark/snowflake/ColumnNameCaseSuite.scala
src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/it/scala/org/apache/spark/sql/SFDataFrameAggregateSuite.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/SnowflakeQuery.scala

This applies the 'limit 1' fix for aggregate expressions pushed down in queries where there is no grouping expression.
Removing the blacklisted item from SFDataFrameAggregateSuite effectively adds a test for this item.

Add limit 1 for aggregates with no grouping expressions

---

src/main/scala/net/snowflake/spark/snowflake/DefaultSource.scala
src/main/scala/net/snowflake/spark/snowflake/LoggerWithTelemetry.scala
src/main/scala/net/snowflake/spark/snowflake/LoggerWrapper.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
src/main/scala/net/snowflake/spark/snowflake/TelemetryReporter.scala
src/main/scala/net/snowflake/spark/snowflake/Utils.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
src/main/scala/net/snowflake/spark/snowflake/io/package.scala
src/main/scala/net/snowflake/spark/snowflake/streaming/SnowflakeSink.scala
src/main/scala/net/snowflake/spark/snowflake/streaming/package.scala
src/main/scala/net/snowflake/spark/snowflake/test/TestHook.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala

This PR is a part of sending spark connector log entries to Telemetry message if an option is enabled.
This PR will make all spark connector logging to go through a logger wrapper object. It will forward the logging request to actual logger and then send log entry as telemetry message if necessary. With the logger wrapper, all the classes to use LOG doesn't need any change.
1. The LoggerWrapper will get a TelemetryReporter instance dynamically for telemetry message, instead of holding an instance reference.
2. TelemetryReporter is a trait, there are 3 concrete implementations: NoopTelemetryReporter, DriverTelemetryReporter and ExecutorTelemetryReporter. TelemetryReporter.getTelemetryReporter() will get an appropriate instance to send log message.
a) NoopTelemetryReporter does nothing, it …

SNOW-205500 Use a logger wrapper for logging for flexibility

---

build.sbt
src/it/scala/org/apache/spark/sql/SFDataFrameAggregateSuite.scala
src/it/scala/org/apache/spark/sql/SFDataFrameSetOperationsSuite.scala
src/it/scala/org/apache/spark/sql/SFDataFrameWindowFramesSuite.scala
src/it/scala/org/apache/spark/sql/SFDataFrameWindowFunctionsSuite.scala

This PR un-blacklists tests from suites inherited from SnowPark, which had broad blacklisting. Since the Spark Connector is capable of running more of these, almost all of the blacklist test cases can be safely run. The remaining blacklisted tests still fail, and so will need to be investigated separately.

Un-blacklist passing tests

---

.github/workflows/IntegrationTest.yml

The IT test on GCP is disabled because environment issue. Now, it looks the env issue has been resolved. re-enable it.

SNOW-177689 Enable IT for GCP

---

src/it/scala/net/snowflake/spark/snowflake/IntegrationEnv.scala
src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/it/scala/net/snowflake/spark/snowflake/io/StageSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala
src/test/scala/net/snowflake/spark/snowflake/io/IOSuite.scala

============
In the PR 282, all special characters are replaced as 'X' when generating a temp stage table name for writing to snowflake database. But unfortunately, some users have the table name to include database and schema name. If below 4 conditions are satisfied in the same time, the write job will fail.
1. Write data frame to a table with OVERWRITE and (usestagingtable=on truncate_table=off (they are default)).
2. table name includes database name and schema name.
3. sfSchema is configured to a different schema
4. The user has privilege to create stage but doesn't have privilege to create table on sfSchema
Fix
====
There is a basic assumption that the table name must be a valid table name for snowflake,
otherwise create table will fail anyway. The safest way to …

SNOW-222104 Fix a writing issue when table name includes Database or Schema

---

src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala

The test case of "write table with different schema" in
TruncateTableSuite needs special test account configuration to run it.
But the account configuration is not done for preprod3/QA account,
so disable this test case for the released SC back-compatibility
regress test.

SNOW-239416 Disable one test case for SC regress test.

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/MiscStatement.scala

1. The original fix is done in https://github.com/snowflakedb/spark-snowflake/pull/253 .
2. The original fix is reverted before releasing SC 2.8.2 in https://github.com/snowflakedb/spark-snowflake/pull/295 .
3. Use “git cherry-pick <hash_code>” to bring back the fix. No merge conflicts happens. Test is PASS.

SNOW-175813 Pushdown coalesce() to snowflake.

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement02.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/DateStatement.scala

Support pushdown for DateSub.
1. SC has already support pushdown fo DateAdd. But no test case is added to test it. Add test case to cover DateAdd().
2. Spark supports DateSub(), Snowflake has NO direct function for this. But Snowflake’s DateAdd() DOES support DateAdd() with negative value which is equivalent to DataSub(). So it can be pushdown too.
3. NOTE: AddMonth() can NOT be pushdown. Both Spark and Snowflake supports AddMonth(). But it can’t be pushdown because there is some different
a. For snowflake ADD_MONTHS: Adds or subtracts a specified number of months to a date or timestamp, preserving the end-of-month information.https://docs.snowflake.com/en/sql-reference/functions/add_months.html
b. For spark ADD_MONTHS:  The behavior for spark 2.3/2.4 and spark 3.0 is different. Spark …

SNOW-179329 Support pushdown for DateSub

---

src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/it/scala/net/snowflake/spark/snowflake/SimpleNewPushdownIntegrationSuite.scala

In spark connector pushdown test,  testPushdown() is commonly used. It will
1. Read the DataFrame from snowflake.
2. Compare the result to be equal to the expected result.
3. The executed query text must match the expected query text.
The read result must the be the same even if the pushdown is disabled. So, add below 2 extra steps for this test function.
1. Disable pushdown and read the DataFrame again.
2. Compare the read result to be equal to the expected result. (Don’t check executed the query text).
This enhancement has found 3 test cases failure. After investigation, they are not actual Spark connector issues. So disable the extra steps for them. Explain them in file changes.

SNOW-241656 Enhance test function testPushdown().

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement02.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/MiscStatement.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/WindowStatement.scala

Snowflake supports rank()/dense_rank() for SELECT query, but doesn’t support them in reading with COPY UNLOAD.
The pushdown analysis is performed in plan generation, it is impossible to know whether use_copy_unload is true or false, so they are pushdown anyway.
If use_copy_unload = true (default is false), the COPY UNLOAD fails. But, SC will retry without pushdown them. So, the job will succeed in the end.
PS: The COPY UNLOAD supported function list can be found at https://docs.snowflake.com/en/user-guide/data-load-transform.html#supported-functions
1. The original fix is done in https://github.com/snowflakedb/spark-snowflake/pull/255
2. The original fix is reverted before releasing SC 2.8.2 in https://github.com/snowflakedb/spark-snowflake/pull/295
3. Use “git cherry-pick <hash_code>” to …

SNOW-177483 Support to pushdown rank()/dense_rank()

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/DefaultSource.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

============
When writing to a table, SC detects the target table existence with desc table <tableName>. Suppose the table name is t1 and sfschema is set as schema1, if there is no schema1.t1 table but public.t1 exists, the desc table t1 will return the table of public.t1. This is described in snowflake document: https://docs.snowflake.com/en/sql-reference/name-resolution.html#resolution-when-schema-omitted-double-dot-notation . But it is not SC's expectation.
Fix proposal
=========
When writing to a snowflake table, SC checks the table existence in current schema only. To play it safe, a new JDBC connection is created and set the search path as current schema only. For example, 
```
conn.createStatement().execute("alter session set search_path='$current'")
```
In …

SNOW-262080 check table existence in current schema only

---

ClusterTest/src/main/scala/net/snowflake/spark/snowflake/ClusterTestResult.scala
src/it/scala/net/snowflake/spark/snowflake/DecimalIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/it/scala/net/snowflake/spark/snowflake/SnowflakeIntegrationSuite.scala
src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala
src/test/scala/net/snowflake/spark/snowflake/MockSF.scala

This is a follow-up PR for https://github.com/snowflakedb/spark-snowflake/pull/328. PR 328 introduced below new function. So `def tableExists(conn: Connection, table: String)` is not necessary any more. But the old function is used in test code. To avoid the PR to have too much change, we introduce this follow-up PR to remove the old function.
The function is not `private[snowflake]`, but the class `JDBCWrapper` is `private[snowflake]`, so it is safe to remove this function.
```
private[snowflake] def tableExists(params: MergedParameters, table: String): Boolean = {
val conn = getConnector(params)
try {
if (params.checkTableExistenceInCurrentSchemaOnly){
conn.createStatement().execute("alter session set search_path='$current'")
}
conn.tableExists(table)
} finally {
conn.close()
}
}
```

SNOW-262080 Remove redundant function JDBCDriver.tableExists(conn,table)

---

src/it/scala/org/apache/spark/sql/SFDataFrameWindowFramesSuite.scala
src/it/scala/org/apache/spark/sql/SFDataFrameWindowFunctionsSuite.scala
src/it/scala/org/apache/spark/sql/snowflake/SFQueryTest.scala
src/it/scala/org/apache/spark/sql/snowflake/SFTestWrapperSparkSession.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/AggregationStatement.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/WindowStatement.scala
src/test/scala/net/snowflake/spark/snowflake/TestUtils.scala

Issue
====
By design, spark connector intends to support pushdown window function: RowNumber, Rank and DenseRank. 
But, if the function is both aggregate and window function, it is also pushdown.
For that case, Spark connector ignored the Window Frame when pushdown these functions.
This may cause wrong result.
This fix is to disable the pushdown if below 2 conditions are satisfied to avoid potential wrong result:
```
// Disable window function pushdown if
// 1. The function are both window function and aggregate function
// 2. User specifies Window Frame. But there is no way to detect
//    whether the window function has Window Frame or not.
//    So we check whether ORDER BY is specified instead.
//    This may disable the window function which has ORDER BY but
//    without Window …
```

SNOW-296738 Disable some Window function pushdown to avoid wrong result.

---

README.md
src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

============
When writing a dataframe with Json format, spark connector specified the column names in the COPY command. For example, 
```
copy into test_table_write_749083442521451968_staging_1100817666 (
CREATE,TABLE,VIEW,INSERT,TEST )
from ( SELECT_FROM_STAGE ) 
FILE_FORMAT = (TYPE = JSON )
```
But, in this customer case, they are using snowflake key word as column name like CREATE. syntax error happens for COPY command.
Fix
======
The fix is straight forward.  We need to quote the column name in the COPY commnand. For example,
```
copy into test_table_write_749083442521451968_staging_617019349 (
"CREATE","TABLE","VIEW","INSERT","TEST" )
from ( SELECT_FROM_STAGE ) 
FILE_FORMAT = ( TYPE = JSON)
```

SNOW-293194 Quote column names when writing with JSON format

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/BasicStatement.scala

The issue is because Spark `EqualNullSafe:  <=> `is pushdown to snowflake as `<=>`. But snowflake doesn’t support this operator.
Snowflake has equivalent function `EQUAL_NULL(left, right)`. So SC can pushdown `EqualNullSafe` as `EQUAL_NULL(left, right)`.

SNOW-330736 Enable to pushdown EqualNullSafe: operator '<=>'

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryHelper.scala

Description
=========
For below use case,  the spark plan is `select c1, first(c2), first(c3) from t1 group by c1`.
But Spark connector pushdown the query as `select c1, c2, c3 from t1 group by c1`. `first()` is missing, so syntax error happens.
```
val df =  spark.sql("select c1, c2, c3 from t1")
df.dropDuplicates("c1").show()
```
The reason why `first()` is ignored is that when `QueryHelper.processedProjections` is generated. 
`e` is an Alias for example `first(C2#2) AS first(C2)#12`, but it has the same exprId with `C2#2`,
so the Alias is converted as a column.
```
val processedProjections: Option[Seq[NamedExpression]] = projections
.map(
p =>
p.map(
e =>
colSet.find(c => c.exprId == e.exprId) match {
case Some(a) =>
AttributeReference(a.name, a.dataType, a.nullable, a.metadata)( …
```

SNOW-304320 Avoid syntax error when processing pushdown of DataFrame.ropDuplicates()

---

src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/it/scala/org/apache/spark/sql/snowflake/SFTestWrapperSparkSession.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

Description
=========
Below DataFrame doesn't have any partition. Currently, the WRITE operation is skipped when writing it to snowflake.
`val emptyDf = Seq.empty[(Int, String)].toDF("key", "value")
`
Analysis
======
I have confirmed to write this DataFrame as CSV file and Parquet file. It generates an empty file for WRITE operation.
So, we will not skip the WRITE operation either. For example,
1. If the target doesn't exists, it will create an empty table.
2. If the target table exists and write mode is OverWrite, a new table is created to overwrite the old table.
Implementation
===========
1. If the dataframe has no partitions
a) If save mode is Append, executes `CREATE  TABLE IF  NOT EXISTS ...`  to create table.
b) If write mode is OverWrite, executes `CREATE OR REPLACE TABLE ...`  to …

SNOW-297134 Support to write a DataFrame without any partition.

---

src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/MiscStatement.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala
src/test/scala/net/snowflake/spark/snowflake/UtilsSuite.scala

This change doesn't affect functionality.
If the conversion is pushdown to snowflake, snowflake will raise conversion error like below. SC will retry without pushdown. The reading will succeed in the end.
But this change will avoid users see a lot of failed query.
```
SQL compilation error:
invalid type [CAST(SUBQUERY_0.D AS FLOAT)] for parameter 'TO_DOUBLE'
```

SNOW-332466 Disable pushdown for converting from DATE/TIMESTAMP to NUMBER

---

.github/docker/build_image.sh
.github/workflows/ClusterTest.yml
.github/workflows/IntegrationTest.yml
ClusterTest/build.sbt
build.sbt
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/NumericStatement.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala

Spark 3.1 has 3 change affects SC pushdown. Below are what's the change and how SC process it.
1. Change constructor for `Union`. It has 2 new parameters: `byName` and `allowMissingCol`. 
Snowflake doesn’t support this spark featured UNION. SC only pushdown UNION if these 2 parameters are FALSE.
```
case class Union(
children: Seq[LogicalPlan],
byName: Boolean = false,
allowMissingCol: Boolean = false)
```
2. Change constructor for UnaryMinus. It has a new parameters `failOnError`.
It defines the behaviour for `Minus` operator for spark when error happens. SC can ignore it.
```
case class UnaryMinus(
child: Expression,
failOnError: Boolean = SQLConf.get.ansiEnabled)
```
3. Change constructor for Rand . It has a new parameter hideSeed.
`hideSeed` is used to avoid printing `seed` in the …

SNOW-358401 Support spark 3.1

---

.github/workflows/ClusterTest.yml
ClusterTest/build.sbt
build.sbt
src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/main/scala/net/snowflake/spark/snowflake/Utils.scala

Currently, Spark connector uses system property to set CLIENT INFO. But this is not reliable in some cases, for example, the user may have no privilege to set system property.
From JDBC 3.13.3, JDBC supports to set CLIENT INFO with JDBC properties.
So, update Spark connector to set it in JDBC properties.
In the same time, bump JDBC version to latest 3.13.3.

SNOW-346101 Set client info with JDBC properties instead of system property

---

src/it/scala/net/snowflake/spark/snowflake/SimpleNewPushdownIntegrationSuite.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala

In order to make sure SORT + LIMIT to return a deterministic result, spark connector needs special handling for SORT + LIMIT to make SORT and LIMIT to be in the same level.  For more details about why they should be in the same level, refer to below document.
1. https://community.snowflake.com/s/article/SELECT-query-with-LIMIT-clause-returns-non-deterministic-result-if-ORDER-BY-clause-exists-in-different-level
2. https://mariadb.com/kb/en/why-is-order-by-in-a-from-subquery-ignored/
But, there is a typo in spark connector pushdown processing which causes the special handling not to be used. This PR is to enable it.
Below `case Limit(limitExpr, Sort(orderExpr, true, _))` is used to handle the special case of SORT + LIMIT, but it is located after `case Limit(limitExpr, _)`. So, it is never …

SNOW-370053 Fix one pushdown issue for LIMIT + SORT.

---

src/it/scala/net/snowflake/spark/snowflake/SimpleNewPushdownIntegrationSuite.scala

The new test case added for SORT + LIMIT fails in the regression test.
The reason is that the test needs there is a large table on the test account.
but there is no such a large table on preprod3 test account.
So, the new test needs to be disabled for regression test.

SNOW-370053 Enable SORT + LIMIT test case for Large data on AWS sfctest0

---

deploy.sh

SNOW-360268
This build script can't run because of `-e` option. 
With `-e`, the script quits because `which sbt` can't find `sbt`.
For details about `-e`, refer to https://tldp.org/LDP/abs/html/options.html

SNOW-360268 Remove the '-e' option for deploy.sh

---

src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala

SNOW-475356
Add below 2 fields to spark connector client_info telemetry. And change to send this message per JDBC connection instead of per JVM.
1. Add `spark_application_id` for spark application ID
2. Add `is_pyspark` for whether it is submitted by pyspark.

SNOW-475356 Add 2 fields to client_info and send it per connection

---

src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/it/scala/net/snowflake/spark/snowflake/io/StageSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
src/main/scala/net/snowflake/spark/snowflake/io/SFInternalStage.scala

Description
=========
The customer reported that if `FORCE_REGIONAL_S3_ENDPOINTS_FOR_PRESIGNED_URLS` is enabled for their account,
the failed to write a DataFrame to a table in snowflake database.
Analysis and fix
============
According to the stacktrace, the error happens when spark connector worker uploading files to internal stage.
But the user can upload data with JDBC. If `FORCE_REGIONAL_S3_ENDPOINTS_FOR_PRESIGNED_URLS` is enabled,
JDBC did special handle to upload file. In general, JDBC use region name in the pre-signed URL to upload to it.
Below is the related code segment in JDBC `SnowflakeS3Client.setupSnowflakeS3Client()`:
```
Region region = RegionUtils.getRegion(stageRegion);
if (region != null) {
if (this.isUseS3RegionalUrl) {
amazonS3Builder.withEndpointConfiguration(
new …
```

SNOW-489598 Support writing for snowflake account with FORCE_REGIONAL_S3_ENDPOINTS_FOR_PRESIGNED_URLS enabled

---

src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

SNOW-495389 Support to write empty DataFrame without CREATE TABLE permission if possible.
=============
Currently, when spark connector writes an empty DataFrame (without any partition), it executes a CREATE TABLE AS SELECT command. In most case, there is no problem because the user needs to have CREATE TABLE privilege.
But in below special case, the user actually doesn't need CREATE TABLE privilege.
1. truncate_table = on
2. usestagingtable = off
3. target table already exists.
Fixing
=====
The fix is to make the DataFrame write to go through the normal DataFrame process instead of executing CTAS for this special case. The original reason to use CTAS is that there is no file uploading happen, the driver can't get a stage prefix. It can be workaround by using a dummy …

SNOW-495389 Support to write empty DataFrame without CREATE TABLE permission if possible.

---

src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala

JDBC only changes the returned datatype, it doesn't change how to get the value from ResultSet.
So SC only needs to support the new type when resolving the schema.

SNOW-614357 Support JDBC datatype TIMESTAMP_WITH_TIMEZONE

---

build.sbt

SNOW-560444 Remove an useless libraries which introduces 2 security Vulnerabilities:
CVE-2020-8908
CVE-2018-10237

SNOW-560444 Remove an useless library

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/Utils.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
src/test/scala/net/snowflake/spark/snowflake/UtilsSuite.scala

SNOW-521177 Don't use new connection to check table existence when saving DF
=============
The customer uses OAuth authentication to connect to snowflake and the token will expire soon after creating the connection. When writing a DataFrame to a table, SC uses a new connection to check the target table existence. The issue is that the token has expired when SC creates the new connection.
Reason to introduce the extra connection
===============================
The extra connection for table existence check is to resolve below case.
1. Suppose user sets `sfSchema = schema1` and will write DF to table `t1`.
2. `t1` doesn't exist in `schema1`, but it exists in schema `public`. The table existence check will return `true` because  unqualified object names are resolved through …

SNOW-521177 Don't use new connection to check table existence when saving DF

---

src/it/scala/net/snowflake/spark/snowflake/VariantTypeSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
src/main/scala/net/snowflake/spark/snowflake/streaming/package.scala

SNOW-635353 Don't use parse_json() for COPY INTO with JSON file.
When writing DF with complex type to a snowflake table, the COPY INTO TABLE command
generated by Spark Connector uses "parse_json($1):<column_name>".
This is inefficient. Spark Connector should use "$1:<column_name>".

SNOW-635353 Don't use parse_json() for COPY INTO with JSON file.

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala
src/main/scala/net/snowflake/spark/snowflake/streaming/SnowflakeSink.scala

These PR added 3 items:
1. Add language name to SPARK_CLIENT_INFO
2. Add spark configuration names if they are not in the white-list. ("N/A" is set in the message for the value)
3. Add SPARK_APPLICATION_ID to all telemetry messages.
4. Introduce `TelemetryMessageSender` for testing purpose.

SNOW-638510 Add some fields to SPARK_CLIENT_INFO

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

SNOW-639416 Add new telemetry message SPARK_INGRESS and add some fields to SPARK_EGRESS
1. The new telemetry message `SPARK_INGRESS` is used to track the data volume written to snowflake. It includes 4 fields: QUERY_ID, DATA_SIZE, ROW_COUNT, APPLICATION_ID
2. Add 3 fields to SPARK_EGRESS which included the DATA_SIZE to read from Snowflake. The 3 new fields are QUERY_ID, ROW_COUNT and APPLICATION_ID to align with SPARK_INGRESS

SNOW-639416 Add new telemetry message SPARK_INGRESS and add update SPARK_EGRESS

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala

SNOW-639519 Add spark libraries to SPARK_CLIENT_INFO
The sample message for spark-submit
---------------------
```
22/08/04 11:44:14 INFO SparkConnectorContext$: Spark Connector system config: {
"spark_connector_version" : "2.10.0",
"spark_version" : "3.2.2",
"application_name" : "Spark SQL basic example",
"scala_version" : "2.12.15",
"java_version" : "11.0.12",
"jdbc_version" : "3.13.14",
"certified_jdbc_version" : "3.13.14",
"os_name" : "Mac OS X",
"max_memory_in_mb" : 1024,
"total_memory_in_mb" : 1024,
"free_memory_in_mb" : 828,
"cpu_cores" : 16,
"spark_application_id" : "local-1659638652697",
"spark_language" : "Scala",
"is_pyspark" : false,
"spark_config" : {
"spark.master" : "local",
"spark.app.startTime" : "N/A",
"spark.some.config.option" : "N/A",
"spark.sql.warehouse.dir" : …
```

SNOW-639519 Add spark libraries to SPARK_CLIENT_INFO

---

build.sbt
src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
src/it/scala/net/snowflake/spark/snowflake/TruncateTableSuite.scala
src/it/scala/org/apache/spark/sql/SnowflakeSparkUtilsSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
src/main/scala/org/apache/spark/sql/snowflake/SnowflakeSparkUtils.scala

SNOW-640144 Add new telemetry message for spark plan statistic.
A sample message for `read from snowflake, and write to snowflake` is:
```
{
"type" : "spark_plan_statistic",
"source" : "spark_connector",
"data" : {
"statistic_info" : [ 
"LogicalRelation:SnowflakeRelation",
"SaveIntoDataSourceCommand:DefaultSource",
"org.apache.spark.sql.catalyst.plans.logical.ReturnAnswer",
"org.apache.spark.sql.catalyst.expressions.AttributeReference"
],
"spark_application_id" : "local-1659985199387"
}
}
```

SNOW-640144 Add new telemetry message for spark plan statistic

---

build.sbt
src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala

SNOW-639519 Update spark libraries to filter out spark SQL.
Changes in this PR:
1. Filter out spark libraries starting with `org.apache.spark.sql.` or `jdk.internal.`
2. Remove the spark libraries caching. I introduced the caching for better performance. But it may cause the actual libraries not to be collected.
3. Remove  "spark.driver.extraClassPath" and  "spark.executor.extraJavaOptions" from the spark configuration whitelist.
The reason is that I found they will cause the telemetry message to be super large e.g. 124K.
4. Add a test case with `Spark ML`

SNOW-639519 Update spark libraries to filter out spark SQL

---

.github/docker/build_image.sh
.github/workflows/ClusterTest.yml
.github/workflows/IntegrationTest_2.12.yml
.github/workflows/IntegrationTest_2.13.yml
.github/workflows/IntegrationTest_gcp_2.12.yml
.github/workflows/IntegrationTest_gcp_2.13.yml
ClusterTest/build.sbt
build.sbt
src/it/resources/log4j2.properties
src/it/scala/net/snowflake/spark/snowflake/IntegrationEnv.scala
src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement02.scala
src/it/scala/net/snowflake/spark/snowflake/SecuritySuite.scala
src/it/scala/org/apache/spark/sql/SFDateFunctionsSuite.scala
src/it/scala/org/apache/spark/sql/snowflake/SFTestSessionBase.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala

For spark 3.3 support, the main change affects  Spark connector is that the Spark 3.3 migrating from `log4j 1` to `log4j 2`.
Spark Connector did below changes to use the new logging system in test
1. Add a default log4j2 configuration file to `src/it/resources/log4j2.properties` which is used by spark automatically.
2. The test cases in `src/it/scala/org/apache/spark/sql/` need to be run in `WARN` level otherwise, the Github action will fail because the test exceed the max time. 
- With `log4j 1`, SC test reconfigure another log properties file with WARN.
- With `log4j 2`, SC dynamically configure log level as WARN in beforeAll and configure it back to INFO in afterAll.
3. The test case `SecuritySuite.scala` needs to configure the output to a file (the default is console). 
- With `log4j …

SNOW-624169 Spark 3.3 support

---

.github/workflows/ClusterTest.yml
ClusterTest/build.sbt
build.sbt
src/main/scala/net/snowflake/spark/snowflake/Utils.scala

1. Update spark connector version as 2.11.0
2. Update JDBC version to 3.13.22
3. Update snowflake-ingest-sdk to 0.10.8
4. Update test dependency: PostgreSQL JDBC Driver to 42.4.1 to avoid vulnerabilities: CVE-2022-31197

SNOW-648611 Update versions

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala

fixes #376
SparkContext.parallelize() doesn't support Int64, instead of which we can use SparkContext.range()

Support to count large table

---

.github/workflows/ClusterTest.yml
.github/workflows/IntegrationTest_2.13.yml
.github/workflows/IntegrationTest_gcp_2.13.yml
ClusterTest/build.sbt
build.sbt
project/plugins.sbt
src/main/scala/net/snowflake/spark/snowflake/Utils.scala

SNOW-691776 Bump versions
1. Update JDBC to use 3.13.24
2. Update SC version to 2.11.1
3. Update Scala 2.13 to 2.13.9
NOTE: Scala 2.13.9 is necessary because there is security issue for 2.13.7.  Refer to https://mvnrepository.com/artifact/org.scala-lang/scala-library/2.13.7

SNOW-691776 Bump versions

---

src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/ProxyInfo.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala

SNOW-664248 Support proxy protocol for S3
Add new option `proxy_protocol` so that customer can configure it. valid values are `http` and `https`.
NOTE: This option only support snowflake AWS account. It is not supported for Azure and GCP.

SNOW-664248 Support proxy protocol for S3

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/it/scala/net/snowflake/spark/snowflake/io/StageSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
src/main/scala/net/snowflake/spark/snowflake/io/SFInternalStage.scala

SNOW-608021 Support S3 VPCE deployment
1. Add a new parameter `S3_STAGE_VPCE_DNS_NAME`. If it is configured, SC will set it for the session.
2. For writing to snowflake, SC needs below changes:
a. GS will send the stage endpoint for `put` command to JDBC. SC driver gets it from JDBC.
b. SC driver passes it to SC executors
c. When SC executor uploads data to the stage, it uses the stage endpoint for uploading.
3. For reading from snowflake, SC dons't need any change because JDBC is used to download the result chunks.
NOTE:
I can only test VPCE support manually because the test with it need VPN to `US West`.

SNOW-608021 Support S3 VPCE deployment

---

src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala

SNOW-692659 Add an option to support returning Long for the Decimal(X, 0) column.
Add a new option: `treat_decimal_as_long` to support returning Long for the Decimal(X, 0) column.
WARNING: if the Decimal value is greater than max value of Long, conversion will happen.

SNOW-692659 Add an option to support returning Long for the Decimal(X, 0) column.

---

src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
src/main/scala/net/snowflake/spark/snowflake/Utils.scala

SNOW-697966 Close JDBC connection
1. Close connection in SnowflakeRelation.buildScanFromSQL() if schema is non-empty
2. Close connection in SnowflakeRelation.getSnowflakeResultSetRDD() if query failed
3. Close connection in Utils.runQuery if query failed

SNOW-697966 Close JDBC connection

---

.github/workflows/ClusterTest.yml
ClusterTest/build.sbt
build.sbt
src/main/scala/net/snowflake/spark/snowflake/Utils.scala
src/test/scala/net/snowflake/spark/snowflake/UtilsSuite.scala

Spark connector: 2.11.2
JDBC: 2.13.28
Ingest SDK: 1.1.0

SNOW-760569 Bump spark connector and dependencies versions

---

.github/workflows/ClusterTest.yml
ClusterTest/build.sbt
build.sbt
src/it/scala/net/snowflake/spark/snowflake/CloudStorageSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Utils.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala

SNOW-763124 Support uploading files with down-scoped token for Snowflake Gcs accounts
The GCS down-scoped token support needs both JDBC and SC to change.
The JDBC change has been included in JDBC 3.13.30. https://github.com/snowflakedb/snowflake-jdbc/pull/1316
This PR also includes:
1. Upgrade the JDBC and SC version to 3.13.30 and 2.11.3.
2. Enhance SC to support down-scoped token for GCP.
The design is https://docs.google.com/document/d/1MlGUyoFOAYEJx6skw2KZfduKp1EPQIJ2SFdsm3emOJ4/edit#

SNOW-763124 Support uploading files with down-scoped token for Gcs

---

src/it/scala/net/snowflake/spark/snowflake/PushdownJoinAndUnion.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/SnowflakeQuery.scala

SNOW-770051 Fix a wrong result issue for crossing schema join/union
The design doc is:
https://docs.google.com/document/d/1Xl8wB5YUMmldftpWIMy9WUm4AfeQoS28bP8ZlPU95lw/edit#heading=h.wmwy5v8eykqd

SNOW-770051 Fix a wrong result issue for crossing schema join/union

---

.github/workflows/ClusterTest.yml
.github/workflows/IntegrationTest_2.12.yml
.github/workflows/IntegrationTest_2.13.yml
.github/workflows/IntegrationTest_gcp_2.12.yml
.github/workflows/IntegrationTest_gcp_2.13.yml
ClusterTest/build.sbt
build.sbt
src/it/scala/net/snowflake/spark/snowflake/SimpleNewPushdownIntegrationSuite.scala
src/it/scala/org/apache/spark/sql/SFDataFrameWindowFramesSuite.scala
src/it/scala/org/apache/spark/sql/SFDataFrameWindowFunctionsSuite.scala
src/it/scala/org/apache/spark/sql/SFDateFunctionsSuite.scala
src/it/scala/org/apache/spark/sql/SnowflakeSparkUtilsSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeConnectorUtils.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/MiscStatement.scala
src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/NumericStatement.scala
src/test/scala/net/snowflake/spark/snowflake/TestUtils.scala

SNOW-824475 Support Spark 3.4
The main changes for Spark 3.4 affects Spark Connector are:
1. Change the last argument for `Cast`
- Old type: `ansiEnabled: Boolean`
- New Type: `evalMode: EvalMode.Value`
- Currently, there are 3 modes: `LEGACY`, `ANSI`, `TRY`
- Support to pushdown, if the mode is `LEGACY`. It will make SC to be in consistent behaviour.
2. Added a `JoinHint` argument for `ScalarSubquery`.
- Spark Connector only pushdown if joinCont is not empty. So the new parameter can be ignored.
3. `PromotePrecision` is removed from Spark 3.4
- So SC only needs to remove the process for this pan node.
4. Added a new argument `ansiEnabled` for `Round`.
- Support to pushdown, if the ansiEnabled is false. It will make SC to be in consistent behaviour.

SNOW-824475 Support Spark 3.4

---

src/it/scala/net/snowflake/spark/snowflake/VariantTypeSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeWriter.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

Support load a Spark dataframe contains both Binary and Variant columns to Snowflake table.

SNOW-903045 Support Dataframe Contains both Binary and Variant Columns

---

src/it/scala/net/snowflake/spark/snowflake/DataTypesIntegrationSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

- Add a new parameter `string_timestamp_format`
- It can overwrite the timestamp format when copy from string dataframe column to timestamp snowflake table column.
- It will be ignored if the source dataframe table has timestamp column

SNOW-1002378 Add new Parameter "string_timestamp_format"

---

src/it/scala/net/snowflake/spark/snowflake/SparkConnectorContextSuite.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
src/main/scala/net/snowflake/spark/snowflake/SparkConnectorContext.scala

Spark triggers `onApplicationEnd` listener earlier than stops tasks. Spark connector cancels all running queries in this listener. Therefore, spark will rerun those canceled queries in the retry.
This PR introduces a new checker, to skip those retries after application closed.

SNOW-1012110 Skip Retry after Application Closed

---

src/it/scala/net/snowflake/spark/snowflake/IssueSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/SnowflakeWriter.scala
src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala

Introduce `trim_space` parameter, which defaults to `false`.
All String columns in the source dataframe will be trimmed before saving to Snowflake table.

SNOW-1045973 Introduce trim_space Parameter

---

src/it/scala/net/snowflake/spark/snowflake/ShareConnectionSuite.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/ServerConnection.scala
src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala

Disable `ABORT_DETACHED_QUERY` at session level by default, to fix `async query canceled after 5 mins` issue.

SNOW-1291653 DIsable abort_detached_query at Session Level

---

ClusterTest/src/main/scala/net/snowflake/spark/snowflake/TestUtils.scala
src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
src/main/scala/net/snowflake/spark/snowflake/ServerConnection.scala
src/test/scala/net/snowflake/spark/snowflake/ParametersSuite.scala

When `sftoken` is not empty, `sfuser` is optional.

SNOW-1515815 Remove the Requirement of SFUSER Parameter when using OAUTH

---

.github/workflows/IntegrationTest_2.12.yml
.github/workflows/IntegrationTest_2.13.yml
.github/workflows/IntegrationTest_gcp_2.12.yml
.github/workflows/IntegrationTest_gcp_2.13.yml

SBT support has been removed from `ubuntu-latest`, fixed it by using early image.

Fix Merge Gate

---

src/it/scala/net/snowflake/spark/snowflake/io/StageSuite.scala
src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala

SNOW-2207811
When using external S3 bucket, the temp aws credentials are not passed correctly.
Manually tested the `test ("manual test with s3 external stage using temporary credentials")`

SNOW-2207811: Fix tmp aws credentials for external S3 bucket
