snowflakedb/spark-snowflake

- src/it/scala/net/snowflake/spark/snowflake/ColumnMappingIntegrationSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
add checker for column mapping function, current version only supports internal stage column mapping.
> Column mapping

- src/it/scala/net/snowflake/spark/snowflake/ColumnMappingIntegrationSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
Don't merge this pull request until all servers updated to 2.51.0
> create temp stage for external storage

- src/it/scala/net/snowflake/spark/snowflake/JDBCSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/SnowflakeQuery.scala
Fixed https://github.com/snowflakedb/spark-snowflake/issues/79
> add parentheses around sql query

- src/it/scala/net/snowflake/spark/snowflake/WindowFunctionSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/MiscStatement.scala
Completed:
- Support row_number function
todo:
- Support filter on Window functions
> support row_number function

- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
Use compatible API of 'asScalaBuffer' to support multiple scala versions. JavaConverters. asScalaBuffer can be used when Scala 2.11 and previous is not needed to support.
> Use compatible API of 'asScalaBuffer' to support multiple scala versions.

- build.sbt
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SFRecordReader.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeRDD.scala
- src/main/scala/net/snowflake/spark/snowflake/io/package.scala
For details description refer to Jira SNOW-119245
> Support supper large data

- src/it/resources/log4j_default.properties
- src/it/scala/net/snowflake/spark/snowflake/SecuritySuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
- src/main/scala/net/snowflake/spark/snowflake/streaming/package.scala
- src/test/scala/net/snowflake/spark/snowflake/MockSF.scala
> Distinguish the log for master and worker for security review.

- .gitignore
- build.sbt
- src/it/scala/net/snowflake/spark/snowflake/SecuritySuite.scala
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SFRecordReader.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeRDD.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
SNOW-126395
This fix also enhances the Spark Connector logging for better readability. "Spark Connector Master" is for master node; "Spark Connector Worker" is for worker node.
> Validate Connector worker reads correct row count for Arrow Format

- src/it/scala/net/snowflake/spark/snowflake/ColumnMappingIntegrationSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/ColumnNameCaseSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/DataTypesIntegrationSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/SFTableNameSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeIntegrationSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/DefaultSource.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
> Use const string as spark connector short name.

- .travis.yml
- src/it/scala/net/snowflake/spark/snowflake/FullNewPushdownIntegrationSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryHelper.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/SnowflakeQuery.scala
Enhance below 2 cases:
1. Support FULL OUTER JOIN pushdown.
2. Support LEFT/RIGHT JOIN even if there are not-null columns.
SNOW-82759
> Support pushdown for OUTER JOIN

- .travis.yml
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeRDD.scala
> Fix travis script, update JDBC to 3.12.0, introduce max file per partition

- build.sbt
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/Conversions.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
> Support to read Double INF/-INF/NaN values.

- src/it/scala/net/snowflake/spark/snowflake/SimpleDateTruncTest.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/DateTruncate.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/package.scala
Converting Scala's TruncTimestamp to SQL DATE_TRUNC - included test script as well.
> Added Pushdown support for truncating date

- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
- src/test/scala/net/snowflake/spark/snowflake/ParametersSuite.scala
See SNOW-120331 (consolidated all commits into one, see #186 )
> add authenticator=oauth support to Spark

- src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/streaming/StreamingSuite.scala
- src/test/scala/net/snowflake/spark/snowflake/BaseTest.scala
SNOW-146803
Add test case for LIKE clause pushdown
Refactor Integration test can run for spark 3.0
> Add test case for LIKE clause pushdown

- .github/docker/Dockerfile
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
Log more details information for Azure storage cloud download & Upload.
> Use fixed Ubuntu version for Cluster Test and enhance logging

- src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeWriter.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
- src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
- src/test/scala/net/snowflake/spark/snowflake/UtilsSuite.scala
1. For BinaryType, the data is converted as Base64 when converting it to CSV
2. Specify the binary type as BASE64 in COPY INTO TABLE command.
3. Log the time used in different phases when writing to snowflake
4. Refactor time format
> Support to write BinaryType column to Snowflake and refactor some log

- deploy.sh
Move the script from snowflake repro to Spark Connector repro
> SNOW-163419 Move Spark Connector release deployment script

- src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
In addition, maintain certified JDBC version internally and
print warning message if the runtime JDBC version is different.
SNOW-165722
SNOW-165728
> SNOW-165722 Send clientInfo telemetry message for spark connector

- src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/DateStatement.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/StringStatement.scala
SNOW-168563
SNOW-166282
SNOW-136558
> Pushdown support for length()/trunc()/date_trunc()

- .github/workflows/IntegrationTest.yml
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
- src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/QueryBuilder.scala
- src/main/scala/net/snowflake/spark/snowflake/streaming/SnowflakeSink.scala
spark_connector_version, spark_version and compile_spark_version
> SNOW-177488 Add 3 common fields for telemetry messages.

- src/it/scala/net/snowflake/spark/snowflake/io/StageSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/streaming/StreamingSuite.scala
For internal stage, the new tests are positive test
For external stage, the new tests are negative test
> SNOW-183129 Add test case for internal/external stages

- ClusterTest/src/main/scala/net/snowflake/spark/snowflake/testsuite/LowMemoryStressSuite.scala
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
- src/test/scala/net/snowflake/spark/snowflake/io/GcpSuite.scala
To release SC 2.8.2 safer, AWS multiple-part upload API is disabled.
Bring back 4 deleted functions to avoid the possibility to break any
customers. 2 functions are in Utils. 2 functions are in Parameters.
> SNOW-199334 Revert SNOW-187770 and bring back 4 deleted public functions

- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeRelation.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
- src/main/scala/net/snowflake/spark/snowflake/io/CloudStorageOperations.scala
- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
- src/main/scala/net/snowflake/spark/snowflake/io/StageReader.scala
- src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
Refer to Jira description for details.
https://snowflakecomputing.atlassian.net/browse/SNOW-206836
> SNOW-206836 Send telemetry message for failed query.

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
Update SC version to 2.8.4
Use JDBC 3.12.17
User snowflake-ingest-sdk 0.10.1
> Prepare to release SC 2.8.4

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
Update SC version to 2.8.5
Use JDBC 3.13.2
> SNOW-276125 Bump SC/JDBC versions

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
Bump snowflake-ingest-sdk version to 0.10.2
> SNOW-346500 Bump SC version to 2.9.0

- src/main/scala/net/snowflake/spark/snowflake/SnowflakeJDBCWrapper.scala
SNOW-394972
Description
=========
Currently, when spark connector needs to get the metadata for table or query, it executes `"SELECT * from ($TABLE_OR_QUERY) where 1 = 2"`. Change to prepare the statement only for efficiency.
Implementation
============
1. Create a new function  `SnowflakeSQLStatement.prepareStatement()` by refactoring `SnowflakeSQLStatement.execute()`.
2. Enhance `DefaultJDBCWrapper.tableMetaDataFromStatement()` to call `prepareStatement()` to get the ResultSetMetadata.
NOTE:
1. There are multiple places to resolve table or query schema. I have confirmed all of them are finally call `tableMetaDataFromStatement().
2. No new test cases are needed since it has been covered by existed test cases.
> SNOW-394972 Get schema by preparing the statement instead of executing it

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
> SNOW-477887 use JDBC 3.13.10

- src/main/scala/net/snowflake/spark/snowflake/io/SnowflakeResultSetRDD.scala
This PR fixes a direct/off-heap memory leak in `ResultIterator`. 
In the current code, the underlying `ResultSet` is only closed when `hasNext` is called and returns `false`. However, there are a few situations where that call might not occur:
1. If the Spark task fails with an exception or is cancelled.
2. If the iterator is not fully iterated. One way that this could happen is if a per-partition limit operator is stacked on top of the Snowflake scan.
Failing to close the `ResultSet` can cause direct/off-heap memory to be leaked (if the Arrow-based ResultSet implementation is being used).
This PR fixes that issue by modifying the code to register a `TaskCompletionListener` to ensure that `data.close()` is called upon task completion or failure. A similar pattern is used in Spark's …
> Use TaskCompletionListener to ensure ResultSet is always closed

- src/it/scala/net/snowflake/spark/snowflake/IntegrationSuiteBase.scala
- src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement02.scala
- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/BasicStatement.scala
SNOW-528863 Fix an issue that literal string "null" is regarded as NULL for pushdown.
> SNOW-528863 Fix an issue that string "null" is regarded as NULL

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
SNOW-544702 Bump SC version to 2.10.0
> SNOW-544702 Bump SC version to 2.10.0

- src/it/scala/net/snowflake/spark/snowflake/PushdownEnhancement01.scala
Customer requests to support UNION BY NAME pushdown.
I found that Spark has optimized the UNION BY NAME as UNION in the spark plan. So, it actually has been supported without any SC enhancement required.
This PR is to add some unit test for `unionByName` pushdown.
> SNOW-548245 (Test Only) Add unit test for unionByName pushdown

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
SNOW-640965 Update spark connector version to 2.10.1
> SNOW-640965 Update spark connector version to 2.10.1

- src/it/scala/net/snowflake/spark/snowflake/IntegrationEnv.scala
- src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
SNOW-643250 Add spark dependencies to SPARK_CLIENT_INFO
Refer to chapter 6 for design discussion.
https://docs.google.com/document/d/1QzYH_1qCFOzu2a_ZoyRj27RzMDhVxU5mZMFNEX7BHeA/edit#heading=h.beye7n5os456
> SNOW-643250 Add spark dependencies to SPARK_CLIENT_INFO

- src/it/scala/net/snowflake/spark/snowflake/SnowflakeResultSetRDDSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
> SNOW-644923 Fix flaky test

- src/it/scala/net/snowflake/spark/snowflake/SnowflakeTelemetrySuite.scala
- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
SNOW-652654 Add spark cluster node/executors count and deployMode to SPARK_CLIENT_INFO
> SNOW-652654 Add spark cluster node/executors count and deployMode to SPARK_CLIENT_INFO

- src/main/scala/net/snowflake/spark/snowflake/SnowflakeTelemetry.scala
SNOW-674428 Fix a NPE when sending telemetry messages.
> SNOW-674428 Fix a NPE when sending telemetry messages.

- src/it/scala/net/snowflake/spark/snowflake/SecuritySuite.scala
SNOW-697097 Fix a security test case issue
> SNOW-697097 Fix a security test case issue

- project/plugins.sbt
SNOW-706809 Update sbt-pgp version to fix release build issue
> SNOW-706809 Update sbt-pgp version to fix release build issue

- .github/workflows/snyk-issue.yml
> CASEC-2322 fix Snyk GHA issue 

- src/main/scala/net/snowflake/spark/snowflake/pushdowns/querygeneration/UnsupportedStatement.scala
SNOW-739785 Send pushdown unsupported telemetry message for UDF
> SNOW-739785 Send pushdown unsupported telemetry message for UDF

- .github/docker/build_image.sh
- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
SNOW-824420 Update SC version to 2.12.0
> SNOW-824420 Update SC version to 2.12.0

- .github/workflows/ClusterTest.yml
- ClusterTest/build.sbt
- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
Update version number to 2.15.0 for release
> SNOW-1063072 Update Version to 2.15.0

- src/it/scala/net/snowflake/spark/snowflake/CloudStorageSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/ProxyInfo.scala
- src/test/scala/net/snowflake/spark/snowflake/MiscSuite01.scala
Fixed issue "setting proxy protocol also changes the connection protocol "
> SNOW-1359291 Fix Proxy Protocol Issue

- src/it/scala/net/snowflake/spark/snowflake/ShareConnectionSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/ServerConnection.scala
SNOW-1572335 Create DataFrame from Provided JDBC Connection
> SNOW-1572335 Create DataFrame from Provided JDBC Connection

- build.sbt
- src/main/scala/net/snowflake/spark/snowflake/Utils.scala
Update JDBC version to 3.24.2 to include a JDBC TrustManager fix.
> SNOW-2129112: Update jdbc version to 3.24.2

- src/it/scala/net/snowflake/spark/snowflake/CopyConfigSuite.scala
- src/main/scala/net/snowflake/spark/snowflake/Parameters.scala
- src/main/scala/net/snowflake/spark/snowflake/io/StageWriter.scala
> SNOW-2157207: Spark connector support copy into force option

- build.sbt
> SNOW-2276083: Update recommended commons-lang version
